use std::collections::BTreeMap;

use anyhow::Result;

use crate::graph::ids::NodeId;
use crate::graph::model::{ItemKind, Node};
use crate::graph::snapshot::OpenedSnapshot;

use super::model::{
    CollectedSkeleton, SkeletonFile, SkeletonItem, SkeletonOptions, SkeletonOutput,
};
use super::source::SourceCache;

pub(super) fn render_source_skeleton(
    snap: &OpenedSnapshot,
    opts: &SkeletonOptions,
    mut collected: CollectedSkeleton,
) -> Result<SkeletonOutput> {
    let mut cache = SourceCache::new(&snap.manifest.workspace_root);
    let mut files = Vec::new();
    let mut total_items = 0;
    let mut total_bytes = 0;

    for source in collected.files {
        let mut content = String::new();
        write_banner(&mut content, snap, opts, &source.crate_name, &source.source_path);

        for item in source.items.iter().filter(|item| item.parent.is_none()) {
            let rendered = cache.render_item(item, opts, &mut collected.diagnostics);
            append_item(&mut content, &rendered);
        }

        let assoc_groups = group_assoc_items(&source.items);
        if !assoc_groups.is_empty() {
            content.push_str("// inherent impl facades; original impl generics/where clauses are not reconstructed\n");
            for (_parent_id, (parent, items)) in assoc_groups {
                content.push_str(&format!("impl {} {{\n", parent.display_name));
                for item in items {
                    let rendered = cache.render_item(item, opts, &mut collected.diagnostics);
                    append_impl_item(&mut content, &rendered);
                }
                content.push_str("}\n\n");
            }
        }

        let bytes = content.len();
        let items = source.items.len();
        total_items += items;
        total_bytes += bytes;
        files.push(SkeletonFile {
            crate_name: source.crate_name,
            source_path: source.source_path,
            skeleton_path: source.skeleton_path,
            content,
            bytes,
            items,
        });
    }

    let total_files = files.len();
    Ok(SkeletonOutput {
        skeleton_dir: ".skeleton".to_string(),
        snapshot_id: snap.manifest.graph_id.clone(),
        files,
        total_files,
        total_items,
        total_bytes,
        diagnostics: collected.diagnostics,
    })
}

fn write_banner(
    content: &mut String,
    snap: &OpenedSnapshot,
    opts: &SkeletonOptions,
    crate_name: &str,
    source_path: &str,
) {
    content.push_str("// @generated by rust-code-mcp crate_skeleton\n");
    content.push_str(&format!("// snapshot: {}\n", snap.manifest.graph_id));
    content.push_str(&format!("// crate: {crate_name}\n"));
    content.push_str(&format!("// source: {source_path}\n"));
    content.push_str(&format!("// include: {}\n", opts.include.join(",")));
    content.push_str(&format!(
        "// include_docs: {}; include_attrs: {}; include_impls: {}; skip_test_items: {}; exclude_vendor: {}\n",
        opts.include_docs,
        opts.include_attrs,
        opts.include_impls,
        opts.skip_test_items,
        opts.exclude_vendor,
    ));
    content.push('\n');
}

fn append_item(content: &mut String, rendered: &str) {
    content.push_str(rendered.trim());
    content.push_str("\n\n");
}

fn append_impl_item(content: &mut String, rendered: &str) {
    let rendered = rendered.trim();
    for line in rendered.lines() {
        if line.trim().is_empty() {
            content.push('\n');
        } else {
            content.push_str("    ");
            content.push_str(line);
            content.push('\n');
        }
    }
}

fn group_assoc_items<'a>(
    items: &'a [SkeletonItem],
) -> BTreeMap<NodeId, (Node, Vec<&'a SkeletonItem>)> {
    let mut groups: BTreeMap<NodeId, (Node, Vec<&SkeletonItem>)> = BTreeMap::new();
    for item in items {
        if !matches!(
            item.node.item_kind,
            Some(ItemKind::Method | ItemKind::AssocConst | ItemKind::AssocType)
        ) {
            continue;
        }
        let Some(parent) = &item.parent else {
            continue;
        };
        if !matches!(
            parent.item_kind,
            Some(ItemKind::Struct | ItemKind::Enum | ItemKind::Union)
        ) {
            continue;
        }
        groups
            .entry(parent.id)
            .or_insert_with(|| (parent.clone(), Vec::new()))
            .1
            .push(item);
    }

    for (_parent_id, (_parent, group_items)) in groups.iter_mut() {
        group_items.sort_by(|a, b| {
            a.node
                .file
                .cmp(&b.node.file)
                .then_with(|| {
                    a.node
                        .span
                        .map(|span| span.0)
                        .cmp(&b.node.span.map(|span| span.0))
                })
                .then_with(|| a.node.qualified_name.cmp(&b.node.qualified_name))
                .then_with(|| a.id.as_bytes().cmp(b.id.as_bytes()))
        });
    }
    groups
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::graph::test_support::shared_snapshot;
    use ra_ap_syntax::SourceFile;

    fn render(opts: SkeletonOptions) -> SkeletonOutput {
        let collected = crate::graph::skeleton::collect::collect_skeleton(
            shared_snapshot(),
            &opts,
        )
        .expect("collect skeleton");
        render_source_skeleton(shared_snapshot(), &opts, collected)
            .expect("render skeleton")
    }

    #[test]
    fn source_renderer_emits_parseable_files() {
        let output = render(SkeletonOptions {
            include: vec!["pub".to_string()],
            ..Default::default()
        });
        assert!(output.total_files > 0);
        assert_eq!(output.total_files, output.files.len());
        for file in output.files {
            let parsed = SourceFile::parse(
                &file.content,
                ra_ap_syntax::Edition::Edition2024,
            );
            assert!(
                parsed.errors().is_empty(),
                "{} parse errors: {:?}\n{}",
                file.skeleton_path,
                parsed.errors(),
                file.content,
            );
            assert_eq!(file.bytes, file.content.len());
        }
    }

    #[test]
    fn source_renderer_does_not_duplicate_trait_associated_items_in_impls() {
        let output = render(SkeletonOptions {
            include: vec!["all".to_string()],
            ..Default::default()
        });
        for file in output.files {
            if file.content.contains("trait ") {
                assert!(
                    !file.content.contains("impl Trait"),
                    "trait associated items should not create synthetic impls in {}",
                    file.skeleton_path,
                );
            }
        }
    }
}
