use std::collections::BTreeMap;

use anyhow::Result;

use crate::graph::ids::NodeId;
use crate::graph::model::{ItemKind, Node};
use crate::graph::snapshot::OpenedSnapshot;

use super::model::{
    CollectedSkeleton, SkeletonFile, SkeletonItem, SkeletonOptions, SkeletonOutput,
};
use super::source::SourceCache;

pub(super) fn render_source_skeleton(
    snap: &OpenedSnapshot,
    opts: &SkeletonOptions,
    mut collected: CollectedSkeleton,
) -> Result<SkeletonOutput> {
    let mut cache = SourceCache::new(&snap.manifest.workspace_root);
    let mut files = Vec::new();
    let mut total_items = 0;
    let mut total_bytes = 0;

    for source in collected.files {
        let mut content = String::new();
        write_banner(&mut content, snap, opts, &source.crate_name, &source.source_path);

        for item in source.items.iter().filter(|item| item.parent.is_none()) {
            let rendered = cache.render_item(snap, item, opts, &mut collected.diagnostics);
            append_item(&mut content, &rendered);
        }

        let assoc_groups = group_assoc_items(&source.items);
        if !assoc_groups.is_empty() {
            content.push_str("// inherent impl facades; original impl generics/where clauses are not reconstructed\n");
            for (_parent_id, (parent, items)) in assoc_groups {
                content.push_str(&format!("impl {} {{\n", parent.display_name));
                for item in items {
                    let rendered = cache.render_item(snap, item, opts, &mut collected.diagnostics);
                    append_impl_item(&mut content, &rendered);
                }
                content.push_str("}\n\n");
            }
        }

        let bytes = content.len();
        let items = source.items.len();
        total_items += items;
        total_bytes += bytes;
        files.push(SkeletonFile {
            crate_name: source.crate_name,
            source_path: source.source_path,
            skeleton_path: source.skeleton_path,
            content,
            bytes,
            items,
        });
    }

    let total_files = files.len();
    Ok(SkeletonOutput {
        skeleton_dir: ".skeleton".to_string(),
        snapshot_id: snap.manifest.graph_id.clone(),
        files,
        total_files,
        total_items,
        total_bytes,
        diagnostics: collected.diagnostics,
    })
}

fn write_banner(
    content: &mut String,
    snap: &OpenedSnapshot,
    opts: &SkeletonOptions,
    crate_name: &str,
    source_path: &str,
) {
    content.push_str("// @generated by rust-code-mcp crate_skeleton\n");
    content.push_str(&format!("// snapshot: {}\n", snap.manifest.graph_id));
    content.push_str(&format!("// crate: {crate_name}\n"));
    content.push_str(&format!("// source: {source_path}\n"));
    content.push_str(&format!("// include: {}\n", opts.include.join(",")));
    content.push_str(&format!(
        "// include_docs: {}; include_attrs: {}; include_impls: {}; skip_test_items: {}; exclude_vendor: {}\n",
        opts.include_docs,
        opts.include_attrs,
        opts.include_impls,
        opts.skip_test_items,
        opts.exclude_vendor,
    ));
    content.push('\n');
}

fn append_item(content: &mut String, rendered: &str) {
    content.push_str(rendered.trim());
    content.push_str("\n\n");
}

fn append_impl_item(content: &mut String, rendered: &str) {
    let rendered = rendered.trim();
    for line in rendered.lines() {
        if line.trim().is_empty() {
            content.push('\n');
        } else {
            content.push_str("    ");
            content.push_str(line);
            content.push('\n');
        }
    }
}

fn group_assoc_items<'a>(
    items: &'a [SkeletonItem],
) -> BTreeMap<NodeId, (Node, Vec<&'a SkeletonItem>)> {
    let mut groups: BTreeMap<NodeId, (Node, Vec<&SkeletonItem>)> = BTreeMap::new();
    for item in items {
        if !matches!(
            item.node.item_kind,
            Some(ItemKind::Method | ItemKind::AssocConst | ItemKind::AssocType)
        ) {
            continue;
        }
        let Some(parent) = &item.parent else {
            continue;
        };
        if !matches!(
            parent.item_kind,
            Some(ItemKind::Struct | ItemKind::Enum | ItemKind::Union)
        ) {
            continue;
        }
        groups
            .entry(parent.id)
            .or_insert_with(|| (parent.clone(), Vec::new()))
            .1
            .push(item);
    }

    for (_parent_id, (_parent, group_items)) in groups.iter_mut() {
        group_items.sort_by(|a, b| {
            a.node
                .file
                .cmp(&b.node.file)
                .then_with(|| {
                    a.node
                        .span
                        .map(|span| span.0)
                        .cmp(&b.node.span.map(|span| span.0))
                })
                .then_with(|| a.node.qualified_name.cmp(&b.node.qualified_name))
                .then_with(|| a.id.as_bytes().cmp(b.id.as_bytes()))
        });
    }
    groups
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::graph::ids::NodeId;
    use crate::graph::model::{Node, NodeKind};
    use super::super::model::SkeletonSourceFile;
    use crate::graph::test_support::shared_snapshot;
    use ra_ap_syntax::SourceFile;

    fn render(opts: SkeletonOptions) -> SkeletonOutput {
        let collected = crate::graph::skeleton::collect::collect_skeleton(
            shared_snapshot(),
            &opts,
        )
        .expect("collect skeleton");
        render_source_skeleton(shared_snapshot(), &opts, collected)
            .expect("render skeleton")
    }

    fn item(id_label: &str, parent: &Node, file: &str, start: u32, qualified: &str) -> SkeletonItem {
        let id = NodeId::from_components(&["skeleton-order", id_label]);
        SkeletonItem {
            id,
            node: Node {
                id,
                kind: NodeKind::Item,
                display_name: qualified.rsplit("::").next().unwrap_or(qualified).to_string(),
                qualified_name: qualified.to_string(),
                crate_id: None,
                parent_id: Some(parent.id),
                item_kind: Some(ItemKind::Method),
                file: Some(file.to_string()),
                span: Some((start, start + 10)),
                visibility: None,
                attributes: Vec::new(),
                crate_target_kind: None,
            },
            parent: Some(parent.clone()),
            visibility: Some("pub".to_string()),
        }
    }

    fn missing_source_item(
        qualified: &str,
        visibility: &str,
        source_path: &str,
    ) -> SkeletonItem {
        let snap = shared_snapshot();
        let (id, mut node) = snap
            .lookup_by_qualified_name(qualified)
            .expect("lookup_by_qualified_name failed")
            .unwrap_or_else(|| panic!("`{qualified}` not in snapshot"));
        node.file = Some(source_path.to_string());
        node.span = Some((0, 1));
        SkeletonItem {
            id,
            node,
            parent: None,
            visibility: Some(visibility.to_string()),
        }
    }

    fn render_missing_source(item: SkeletonItem, source_path: &str) -> SkeletonOutput {
        let crate_name = item
            .node
            .qualified_name
            .split("::")
            .next()
            .unwrap_or_default()
            .to_string();
        render_source_skeleton(
            shared_snapshot(),
            &SkeletonOptions::default(),
            CollectedSkeleton {
                files: vec![SkeletonSourceFile {
                    crate_name,
                    source_path: source_path.to_string(),
                    skeleton_path: format!(".skeleton/{source_path}"),
                    items: vec![item],
                }],
                diagnostics: Vec::new(),
            },
        )
        .expect("render skeleton")
    }

    #[test]
    fn source_renderer_emits_parseable_files() {
        let output = render(SkeletonOptions {
            include: vec!["pub".to_string()],
            ..Default::default()
        });
        assert!(output.total_files > 0);
        assert_eq!(output.total_files, output.files.len());
        for file in output.files {
            let parsed = SourceFile::parse(
                &file.content,
                ra_ap_syntax::Edition::Edition2024,
            );
            assert!(
                parsed.errors().is_empty(),
                "{} parse errors: {:?}\n{}",
                file.skeleton_path,
                parsed.errors(),
                file.content,
            );
            assert_eq!(file.bytes, file.content.len());
        }
    }

    #[test]
    fn missing_source_function_fallback_uses_persisted_signature() {
        let source_path = "src/__missing_signature_fallback.rs";
        let item = missing_source_item(
            "rmc_graph::graph::loader::load",
            "pub",
            source_path,
        );
        let output = render_missing_source(item, source_path);
        let file = output.files.first().expect("rendered file");
        assert!(
            file.content.contains(
                "pub fn load(directory: &Path) -> Result<LoadedWorkspace, Error> { /* ... */ }"
            ),
            "{}",
            file.content,
        );
        assert!(!file.content.contains("pub fn load()"));
        assert!(
            output
                .diagnostics
                .iter()
                .any(|diagnostic| diagnostic.message.contains("could not read source")),
            "expected missing source diagnostic, got {:?}",
            output.diagnostics,
        );
        let parsed = SourceFile::parse(
            &file.content,
            ra_ap_syntax::Edition::Edition2024,
        );
        assert!(parsed.errors().is_empty(), "{:?}", parsed.errors());
    }

    #[test]
    fn missing_source_static_fallback_uses_persisted_metadata() {
        let source_path = "src/__missing_static_fallback.rs";
        let qualified = "rmc_server::semantic::SEMANTIC";
        let item = missing_source_item(qualified, "pub(crate)", source_path);
        let snap = shared_snapshot();
        let metadata = snap
            .static_metadata(item.id)
            .expect("static_metadata failed")
            .expect("expected static metadata");
        let output = render_missing_source(item, source_path);
        let file = output.files.first().expect("rendered file");
        let mutability = if metadata.is_mut { "mut " } else { "" };
        let expected = format!(
            "pub(crate) static {mutability}SEMANTIC: {} = todo!();",
            metadata.type_string,
        );
        assert!(file.content.contains(&expected), "{}", file.content);
        assert!(!file.content.contains("static SEMANTIC: () = ();"));
        let parsed = SourceFile::parse(
            &file.content,
            ra_ap_syntax::Edition::Edition2024,
        );
        assert!(parsed.errors().is_empty(), "{:?}", parsed.errors());
    }

    #[test]
    fn source_renderer_does_not_duplicate_trait_associated_items_in_impls() {
        let output = render(SkeletonOptions {
            include: vec!["all".to_string()],
            ..Default::default()
        });
        for file in output.files {
            if file.content.contains("trait ") {
                assert!(
                    !file.content.contains("impl Trait"),
                    "trait associated items should not create synthetic impls in {}",
                    file.skeleton_path,
                );
            }
        }
    }

    #[test]
    fn synthetic_impl_members_are_deterministically_ordered() {
        let parent_id = NodeId::from_components(&["skeleton-order", "Host"]);
        let parent = Node {
            id: parent_id,
            kind: NodeKind::Item,
            display_name: "Host".to_string(),
            qualified_name: "test_crate::Host".to_string(),
            crate_id: None,
            parent_id: None,
            item_kind: Some(ItemKind::Struct),
            file: Some("src/lib.rs".to_string()),
            span: Some((0, 10)),
            visibility: None,
            attributes: Vec::new(),
            crate_target_kind: None,
        };
        let unsorted = vec![
            item("c", &parent, "src/z.rs", 30, "test_crate::Host::c"),
            item("a", &parent, "src/a.rs", 20, "test_crate::Host::a"),
            item("b", &parent, "src/a.rs", 10, "test_crate::Host::b"),
        ];
        let groups = group_assoc_items(&unsorted);
        let group = &groups.get(&parent_id).expect("host group").1;
        let names: Vec<&str> = group
            .iter()
            .map(|item| item.node.qualified_name.as_str())
            .collect();
        assert_eq!(
            names,
            vec![
                "test_crate::Host::b",
                "test_crate::Host::a",
                "test_crate::Host::c",
            ],
        );
    }
}
