use anyhow::Result;

use crate::graph::item_kind_short_label;
use crate::graph::snapshot::OpenedSnapshot;

use super::model::{
    CollectedSkeleton, SkeletonFile, SkeletonOptions, SkeletonOutput,
};

pub(super) fn render_stub_skeleton(
    snap: &OpenedSnapshot,
    opts: &SkeletonOptions,
    collected: CollectedSkeleton,
) -> Result<SkeletonOutput> {
    let mut files = Vec::new();
    let mut total_items = 0;
    let mut total_bytes = 0;

    for source in collected.files {
        let mut content = String::new();
        content.push_str("// @generated by rust-code-mcp crate_skeleton\n");
        content.push_str(&format!("// snapshot: {}\n", snap.manifest.graph_id));
        content.push_str(&format!("// crate: {}\n", source.crate_name));
        content.push_str(&format!("// source: {}\n", source.source_path));
        content.push_str(&format!("// include: {}\n", opts.include.join(",")));
        content.push_str(&format!(
            "// include_docs: {}; include_attrs: {}; include_impls: {}; skip_test_items: {}; exclude_vendor: {}\n",
            opts.include_docs,
            opts.include_attrs,
            opts.include_impls,
            opts.skip_test_items,
            opts.exclude_vendor,
        ));
        content.push_str("//\n");

        for item in &source.items {
            let kind = item
                .node
                .item_kind
                .map(item_kind_short_label)
                .unwrap_or("Item");
            match item.visibility.as_deref() {
                Some(vis) => content.push_str(&format!(
                    "// item: {} [{}; {}]\n",
                    item.node.qualified_name, kind, vis
                )),
                None => content.push_str(&format!(
                    "// item: {} [{}]\n",
                    item.node.qualified_name, kind
                )),
            }
        }

        let bytes = content.len();
        let items = source.items.len();
        total_items += items;
        total_bytes += bytes;
        files.push(SkeletonFile {
            crate_name: source.crate_name,
            source_path: source.source_path,
            skeleton_path: source.skeleton_path,
            content,
            bytes,
            items,
        });
    }

    let total_files = files.len();
    Ok(SkeletonOutput {
        skeleton_dir: ".skeleton".to_string(),
        snapshot_id: snap.manifest.graph_id.clone(),
        files,
        total_files,
        total_items,
        total_bytes,
        diagnostics: collected.diagnostics,
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::graph::test_support::shared_snapshot;
    use ra_ap_syntax::SourceFile;

    fn render(opts: SkeletonOptions) -> SkeletonOutput {
        let collected = crate::graph::skeleton::collect::collect_skeleton(
            shared_snapshot(),
            &opts,
        )
        .expect("collect skeleton");
        render_stub_skeleton(shared_snapshot(), &opts, collected)
            .expect("render skeleton")
    }

    #[test]
    fn stub_renderer_emits_parseable_comment_only_files() {
        let output = render(SkeletonOptions {
            include: vec!["pub".to_string()],
            ..Default::default()
        });
        assert!(output.total_files > 0);
        assert_eq!(output.total_files, output.files.len());
        for file in output.files {
            let parsed = SourceFile::parse(
                &file.content,
                ra_ap_syntax::Edition::Edition2024,
            );
            assert!(parsed.errors().is_empty());
            assert!(file.content.contains("// item: "));
            assert_eq!(file.bytes, file.content.len());
        }
    }
}
